server:
 port: 8989
 
eureka:
 client:
   register-with-eureka: true
   fetch-registry : true
   service-url:
     defaultZone: http://localhost:8761/eureka
spring:     
  application:
   name: GATEWAY-SERVICE
  cloud:   
   gateway:
    routes:
     - id: user-service-routes
       uri: http://localhost:9191
       predicates:
         - Path=/user/**

     - id: transaction-service-routes
       uri: http://localhost:9292
       predicates:
         - Path=/transaction/**
           
management:
  endpoints:
    web:
     exposure:
        include: hystrix.stream

        
          