#Eureka Client Details 
eureka:
 client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
     defaultZone: http://localhost:8761/eureka
#Server Configuration    
server:
  port: 9292
# App and DB Configuration   
spring:     
  application:
   name: TRANSACTION-SERVICE  
  data: 
   mongodb:
       uri: ${MONGODB_URI}
       database: Assignment   
 
    